version: "3.9"
services:
  exb:
    image: jageagle/esri-exb:exb-1.10
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../builder/rainfall-radar:/home/node/ArcGISExperienceBuilder/client/your-extensions/widgets/rainfall-radar/
      # - ../themes:/home/node/ArcGISExperienceBuilder/client/your-extensions/themes/
      # - ../config:/home/node/ArcGISExperienceBuilder/server/public/apps/0
    command: bash -c "npm start & (cd ../client && npm start)"
